### ISSUE TITLE
its not installeble for Nopcommerce 4.50

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#19]
Hello,
I am trying to install that plugin from upload plugin section.

And i am got that error in logs when restart for install:

`info: FluentMigrator.Runner.MigrationRunner[1000]
      SchemaMigration migrating
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1004]
      Beginning Transaction
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1003]
      BEGIN TRANSACTION
info: FluentMigrator.Runner.MigrationRunner[1004]
      CreateTable GoogleProductRecord
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1003]
      CREATE TABLE [dbo].[GoogleProductRecord] ([Id] INT NOT NULL IDENTITY(1,1), [ProductId] INT NOT NULL, [Taxonomy] NVARCHAR(MAX), [CustomGoods] BIT NOT NULL, [Gender] NVARCHAR(MAX), [AgeGroup] NVARCHAR(MAX), [Color] NVARCHAR(MAX), [Size] NVARCHAR(MAX), [Material] NVARCHAR(MAX), [Pattern] NVARCHAR(MAX), CONSTRAINT [PK_GoogleProductRecord] PRIMARY KEY ([Id]))
fail: FluentMigrator.Runner.MigrationRunner[0]
      An error occured executing the following sql:
      CREATE TABLE [dbo].[GoogleProductRecord] ([Id] INT NOT NULL IDENTITY(1,1), [ProductId] INT NOT NULL, [Taxonomy] NVARCHAR(MAX), [CustomGoods] BIT NOT NULL, [Gender] NVARCHAR(MAX), [AgeGroup] NVARCHAR(MAX), [Color] NVARCHAR(MAX), [Size] NVARCHAR(MAX), [Material] NVARCHAR(MAX), [Pattern] NVARCHAR(MAX), CONSTRAINT [PK_GoogleProductRecord] PRIMARY KEY ([Id]))
      The error was Veritabannda 'GoogleProductRecord' adl bir nesne zaten var.
      
      System.Exception: An error occured executing the following sql:
      CREATE TABLE [dbo].[GoogleProductRecord] ([Id] INT NOT NULL IDENTITY(1,1), [ProductId] INT NOT NULL, [Taxonomy] NVARCHAR(MAX), [CustomGoods] BIT NOT NULL, [Gender] NVARCHAR(MAX), [AgeGroup] NVARCHAR(MAX), [Color] NVARCHAR(MAX), [Size] NVARCHAR(MAX), [Material] NVARCHAR(MAX), [Pattern] NVARCHAR(MAX), CONSTRAINT [PK_GoogleProductRecord] PRIMARY KEY ([Id]))
      The error was Veritabannda 'GoogleProductRecord' adl bir nesne zaten var.
      
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Veritabannda 'GoogleProductRecord' adl bir nesne zaten var.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
         at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
         at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
      ClientConnectionId:a6e3c4f0-03d1-480b-88ae-fabc4b5818c0
      Error Number:2714,State:6,Class:16
         --- End of inner exception stack trace ---
         at FluentMigrator.Runner.Processors.ProcessorBase.ReThrowWithSql(Exception ex, String sql)
         at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
         at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Process(String sql)
         at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateTableExpression expression)
         at FluentMigrator.Expressions.CreateTableExpression.ExecuteWith(IMigrationProcessor processor)
         at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
         at FluentMigrator.Runner.StopWatch.Time(Action action)
         at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1004]
      Rolling back transaction
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1003]
      ROLLBACK TRANSACTION
info: FluentMigrator.Runner.MigrationRunner[1000]
      SlidersDataMigration migrating
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1004]
      Beginning Transaction
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1003]
      BEGIN TRANSACTION
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1004]
      Rolling back transaction
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1003]
      ROLLBACK TRANSACTION
`

**Comment by mk148a** [comment]
its error for "the db is already in"
